dirs: 
  - .
ignorePatterns:
  - pattern: "/github/"
  - pattern: "./actions"
  - pattern: "./blob"
  - pattern: "./issues"
  - pattern: "./discussions"
  - pattern: "./pulls"
  - pattern: "https:\/\/platform.openai.com"
  - pattern: "https:\/\/outlook.office.com/bookings"
excludedDirs:
  # Folders which include links to localhost, since it's not ignored with regular expressions
  - ./python/samples/demos/telemetry
  - ./python/samples/demos/process_with_dapr
  - ./dotnet/samples/Demos/ProcessWithDapr
  - ./dotnet/samples/Demos/CopilotAgentPlugins
baseUrl: https://github.com/microsoft/semantic-kernel/
aliveStatusCodes: 
  - 200
  - 206
  - 429
  - 500
  - 503
useGitIgnore: true
