dirs: 
  - .
ignorePatterns:
  - pattern: "/github/"
  - pattern: "./actions"
  - pattern: "./blob"
  - pattern: "./issues"
  - pattern: "./discussions"
  - pattern: "./pulls"
  - pattern: "https:\/\/platform.openai.com"
  - pattern: "https:\/\/outlook.office.com/bookings"
excludedDirs:
  # Folders which include links to localhost, since it's not ignored with regular expressions
  - ./python/samples/demos/telemetry
  - ./python/samples/demos/process_with_dapr
  - ./dotnet/samples/Demos/ProcessWithDapr
  - ./dotnet/samples/Demos/CopilotAgentPlugins
  # Exclude folders that contain documents with links prone to becoming broken and temporarily unavailable. This should be removed when the link checker is implemented as a background job that does not block PRs.
  - ./docs/decisions
  - ./dotnet/samples
  - ./dotnet/src/IntegrationTests # Cannot reach https://www.microsoft.com/en-us/bing/apis/bing-web-search-api Status: 404" location:{path:"dotnet/src/IntegrationTests/README.md"
  - ./dotnet/src/Experimental/Orchestration.Flow.IntegrationTests # Cannot reach https://www.microsoft.com/en-us/bing/apis/bing-web-search-api Status: 404" location:{path:"dotnet/src/Experimental/Orchestration.Flow.IntegrationTests/README.md"
  - ./python/samples
baseUrl: https://github.com/microsoft/semantic-kernel/
aliveStatusCodes: 
  - 200
  - 206
  - 429
  - 500
  - 503
useGitIgnore: true
