trigger:
- main

# no PR triggers
pr: none

pool:
  vmImage: 'windows-latest'

steps:
- task: CredScan@2
  inputs:
    toolMajorVersion: 'V2'
- task: ESLint@1
  inputs:
    Configuration: 'recommended'
    TargetType: 'eslint'
    ErrorLevel: 'warn'

- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

# - task: Semmle@0
#   env: 
#     SYSTEM_ACCESSTOKEN: $(System.AccessToken)
#   inputs:
#     sourceCodeDirectory: '$(Build.SourcesDirectory)'
#     language: 'tsandjs'
#     includeNodeModules: true
#     querySuite: 'Recommended'
#     timeout: '1800'
#     ram: '16384'
# addProjectDirToScanningExclusionList: true

- task: Semmle@1
  env: 
     SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    sourceCodeDirectory: '$(Build.SourcesDirectory)'
    language: 'csharp'
    buildCommandsString: '$(Agent.ToolsDirectory)\dotnet\dotnet.exe restore $(BUILD.SourcesDirectory)\dotnet\SK-dotnet.sln#$(Agent.ToolsDirectory)\dotnet\dotnet.exe build $(BUILD.SourcesDirectory)\dotnet\SK-dotnet.sln'
    querySuite: 'Recommended'
    timeout: '1800'
    ram: '16384'
    addProjectDirToScanningExclusionList: true

# Both versions of Semmle (0 and 1) aren't required
# Either one is fine. The latest version will show up as
# Semmle@1 while older version will be listed as Semmle@0
# By default, version 1 (@1) will be added to pipeline
# This sample contains both, just for sample purposes

# Usage of System.AccessToken is only required for uploading
# results to CodeQL servers via variable LGTM.UploadSnapshot = true
# If you want to analyze errors on your own or if LGTM.UploadSnapshot = false,
# then passing this environment variable is not required.

#######################################################
# Highly Discouraged, only for backward compatibility #
#######################################################
# When code is hosted on GitHub and build pipeline is created on ADO then a PAT token can be used in place of AccessToken as part of environment variable
# SYSTEM_ACCESSTOKEN: $(PATToken)
# Where PATToken is name of the variable and value contains the actual PAT token generated by user

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'

- task: PublishSecurityAnalysisLogs@2
  inputs:
    ArtifactName: 'CodeAnalysisLogs'
    ArtifactType: 'Container'
    AllTools: true
    ToolLogsNotFoundAction: 'Standard'
