// Copyright (c) Microsoft. All rights reserved.
package com.microsoft.semantickernel.textcompletion;

import com.azure.ai.openai.OpenAIAsyncClient;
import com.microsoft.semantickernel.Kernel;
import com.microsoft.semantickernel.TextAIService;
import com.microsoft.semantickernel.builders.Buildable;
import com.microsoft.semantickernel.builders.SemanticKernelBuilder;
import com.microsoft.semantickernel.implementation.ServiceLoadUtil;
import com.microsoft.semantickernel.orchestration.PromptExecutionSettings;

import java.util.List;

import javax.annotation.Nullable;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

/**
 * Interface for text completion services
 */
public interface TextGenerationService extends Buildable, TextAIService {

    /**
     * Creates a completion for the prompt and settings.
     *
     * @param prompt            The prompt to complete.
     * @param executionSettings Request settings for the completion API
     * @param kernel            The {@code Kernel} containing services, plugins, and other state for
     *                         use throughout the operation.
     * @return Text generated by the remote model
     */
    Mono<List<TextContent>> getTextContentsAsync(
        String prompt,
        @Nullable PromptExecutionSettings executionSettings,
        @Nullable Kernel kernel);

    /**
     * Get streaming results for the prompt using the specified execution settings. Each modality
     * may support for different types of streaming contents.
     *
     * @param prompt            The prompt to complete.
     * @param executionSettings The AI execution settings (optional).
     * @param kernel            The {@code Kernel} containing services, plugins, and other state for
     *                         use throughout the operation.
     * @return Streaming list of different completion streaming string updates generated by the
     * remote model
     */
    Flux<StreamingTextContent> getStreamingTextContentsAsync(
        String prompt,
        @Nullable PromptExecutionSettings executionSettings,
        @Nullable Kernel kernel);

    /**
     * Get the builder for the TextGenerationService
     * @return The builder
     */
    static Builder builder() {
        return ServiceLoadUtil.findServiceLoader(Builder.class,
            "com.microsoft.semantickernel.aiservices.openai.textcompletion.OpenAITextGenerationService$Builder")
            .get();
    }

    /**
     * Builder for a TextGenerationService
     */
    abstract class Builder implements SemanticKernelBuilder<TextGenerationService> {

        @Nullable
        protected String modelId;
        @Nullable
        protected OpenAIAsyncClient client;
        @Nullable
        protected String serviceId;

        /**
         * Sets the model ID for the service
         *
         * @param modelId The model ID
         * @return The builder
         */
        public Builder withModelId(String modelId) {
            this.modelId = modelId;
            return this;
        }

        /**
         * Sets the OpenAI client for the service
         *
         * @param client The OpenAI client
         * @return The builder
         */
        public Builder withOpenAIAsyncClient(OpenAIAsyncClient client) {
            this.client = client;
            return this;
        }

        /**
         * Sets the service ID for the service
         *
         * @param serviceId The service ID
         * @return The builder
         */
        public Builder withServiceId(String serviceId) {
            this.serviceId = serviceId;
            return this;
        }

        @Override
        public abstract TextGenerationService build();

    }
}
