classDiagram

    ChatHistory

    AgentChatState --> ChatHistory
    AgentChannelState --* AgentChatState
    AgentReference --* AgentChatState
    class AgentChatState {
        ChatHistory History
        Iterable~AgentReference~ Agents
        Iterable~AgentChannelState~ Channels
    }

    class AgentChannelState {
        +text ChannelKey
        +text ChannelState
    }

    class AgentReference {
        +text AgentId
        +text? AgentName
        +text AgentType
    }