classDiagram

    ChatHistory

    AgentChatState --> ChatHistory
    AgentChannelState --* AgentChatState
    class AgentChatState {
        ChatHistory History
        IEnumerable~AgentChannelState~ Channels
    }

    class AgentChannelState {
        +string ChannelKey
        +string ChannelState
    }