classDiagram

    class OpenAIThreadCreationOptions {
        List~string~? CodeInterpterFileIds
        IReadOnlyList<ChatMessageContent>? Messages
        string? VectorStoreId
        Dictionary~string, string~? Metadata
    }