// Copyright (c) Microsoft. All rights reserved.

namespace Microsoft.SemanticKernel.Planning.Handlebars;

/// <summary>
/// Configuration for Handlebars planner instances.
/// </summary>
public sealed class HandlebarsPlannerOptions : PlannerOptions
{
    // Inherited:
    // - ExcludedPlugins
    // - ExcludedFunctions
    // - GetAvailableFunctionsAsync

    // TODO: do we want to allow overriding template?

    /// <summary>
    /// Gets or sets the last plan generated by the planner.
    /// </summary>
    public HandlebarsPlan? LastPlan { get; set; }

    /// <summary>
    /// Gets or sets the last error that occurred during planning.
    /// </summary>
    public string? LastError { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether loops are allowed in the plan.
    /// </summary>
    public bool AllowLoops { get; set; } = true;

    /// <summary>
    /// Initializes a new instance of the <see cref="HandlebarsPlannerOptions"/> class.
    /// </summary>
    public HandlebarsPlannerOptions(
        HandlebarsPlan? lastPlan = default,
        string? lastError = default,
        bool allowLoops = true
    )
    {
        this.LastPlan = lastPlan;
        this.LastError = lastError;
        this.AllowLoops = allowLoops;
    }
}
