<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SemanticKernel.Connectors.Milvus.UnitTests</AssemblyName>
    <RootNamespace>SemanticKernel.Connectors.Milvus.UnitTests</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);SKEXP0001;SKEXP0020</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Testcontainers.Milvus" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\VectorData\Milvus\Milvus.csproj" />
  </ItemGroup>
</Project>
