name: Python Start Release on ADO

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release"
        required: true

permissions:
  contents: read
  id-token: "write"

jobs:
  python-build-assets:
    name: Trigger ADO Pipeline for Python Release
    runs-on: ubuntu-latest
    environment: "integration"
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Start DevOps pipeline
        uses: azure/cli@v2
        with:
          inlineScript: |
            az pipelines run --id 308 --org ${{ vars.ADO_PROJECT_URL }} --project semantic-kernel --parameters tag=${{ inputs.tag }} delay=0
