# Check pull requests for typos.
#
# Configuration: .github/_typos.toml
#
# Info:          https://github.com/marketplace/actions/typos-action
# Local install: brew install typos-cli
# Local install: conda install typos
# Local run:     typos -c .github/_typos.toml

name: Spell Check

on:
  workflow_dispatch:
  pull_request:
    branches: ["main", "feature*"]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get changed files
        id: changed-files
        if: github.event_name == 'pull_request'
        uses: jitterbit/get-changed-files@v1

      - name: Use custom config file
        uses: crate-ci/typos@v1.44.0
        with:
          files: ${{ github.event_name == 'pull_request' && steps.changed-files.outputs.added_modified || '.' }}
          config: .github/_typos.toml
          write_changes: false
